name: front CI
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              
            - name: HTML5Validator
              uses: Cyb3r-Jak3/html5validator-action@v7.2.0
              with:
                root: .
                css: true